### ISSUE TITLE
Service data

### ISSUE THREAD

**Issue by gvigroux** [berrywhite96/lovelace-shutter-row#20]
When using the UI to configure an action, the default keyword used for data sent to the service is "data". It seems it should be "service_data"

I've had to update it myself in the code to have this working

**Comment by berrywhite96** [comment]
That's funny because the yaml data is generated by an dependency and the execution of the service too, so I never chose the keyword.
I will look into it, besides I saw that the three custom actions are always `move_down_button`.

Not really put a lot of love in it, I am just not a fan of the UI configuration.

**Comment by berrywhite96** [comment]
Fixed in 0.3.1 and onwards.
